@Sentri.Api_HostAddress = https://localhost:7002

POST {{Sentri.Api_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json
{
  "email": "fernandes.diegod@gmail.com",
  "name": "Diego Fernandes",
  "password": "Abc123"
}

###

# @name login
POST {{Sentri.Api_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json
{
  "email": "fernandes.diegod@gmail.com",
  "password": "Abc123"
}

###

GET {{Sentri.Api_HostAddress}}/api/providers
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}

###

# @name createProvider
POST {{Sentri.Api_HostAddress}}/api/providers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "name": "OpenAI",
  "monthlyBudget": 500.00,
  "warningThreshold": 2
}

###

POST {{Sentri.Api_HostAddress}}/api/expenses/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "amount": 800.00,
  "providerId": "{{createProvider.response.body.$.id}}"
}
